#!/usr/bin/env bash
cd -P "$(dirname "$0")/.." || exit

POETRY_HOME=$(poetry env info -p)

if [[ $DEBUG == "true" ]]; then
    poetry install --no-root
else
    poetry install --no-root --only main
fi
export PATH="$POETRY_HOME/bin:$PATH"
