#!/usr/bin/env bash
cd -P "$(dirname "$0")/.."

TMUX="" \
	tmux new-session \
	-e PATH="$PATH" \
	-e INSIDE_NIX="$INSIDE_NIX" \
	-e DEBUG="$DEBUG" '
  echo ""                           &&
  echo "http://localhost:5000/docs" &&
  read
' \; split-window -h -p 65 '
  docker compose up db
' \; split-window -f -p 80 '
    find app tests -name "*.py" -print | entr -r ./scripts/test
    read
' \; split-window -h -p 50 '
  function ctrl_c() {
    docker compose down
    tmux kill-session
  }
  trap ctrl_c INT
  ./scripts/start-api || true
  read
'
