#!/usr/bin/env bash
cd -P "$(dirname "$0")/.." || exit

URL=$(git config remote.origin.url)
USERNAME=${URL%/*}
USERNAME=${USERNAME#*:}
REPO=$(basename "$URL")
REPO=${REPO%.*}

if [[ $INSIDE_NIX == "true" ]]; then
    ./scripts/update || true
    if [[ $DEBUG == "true" ]]; then
        fastapi dev --host 0.0.0.0 app/app.py
    else
        fastapi run --host 0.0.0.0 app/app.py
    fi
else
    docker run --rm -it                    \
        -v      .:/app                     \
        --mount source=nix,target=/nix     \
        --mount source=cache,target=/cache \
        -p      8000:8000                  \
        ghcr.io/"$USERNAME"/"$REPO":latest \
        /app/scripts/start-api
fi
