#!/usr/bin/env bash
cd -P "$(dirname "$0")/.." || exit

TMUX="" tmux new-session \
	-e PATH="$PATH" \
	-e INSIDE_DOCKER="$INSIDE_DOCKER" \
	-e INSIDE_NIX="$INSIDE_NIX" \
	-e DEBUG="$DEBUG" '
  echo ""                            &&
  echo "http://localhost:8000"       &&
  echo "http://localhost:8000/docs"  &&
  echo "http://localhost:8000/redoc" &&
  read
' \; split-window -h -p 65 '
  #docker compose up db
  read
' \; split-window -f -p 80 '
  ./scripts/start-api || true
  read
' \; split-window -h -p 50 '
  function ctrl_c() {
    #docker compose down
    tmux kill-session
  }
  trap ctrl_c INT
  ./scripts/watch || true
  read
'
